### ISSUE TITLE
Request for result files

### ISSUE THREAD

**Issue by Daikenan** [huanglianghua/GlobalTrack#10]
Hi,
Could you please provide your result files(LaSOT, TLP..) available?

**Comment by huanglianghua** [comment]
Hi, thanks for the advice.
We will provide the tracking results on all typical tracking datasets within this week.

**Comment by huanglianghua** [comment]
@Daikenan Hi, we have released the tracking results of GlobalTrack on several benchmarks. Please refer to the updated README.md for details. Thanks.
