### ISSUE TITLE
COCO 、LaSOT、GOT10K  preprocess

### ISSUE THREAD

**Issue by cifar10** [huanglianghua/GlobalTrack#13]
Thank you for the author's code. Do we need to preprocess the coco, LaSOT, GOT10K data when reproducing the code ourselves, or just put it in the corresponding folder?

**Comment by huanglianghua** [comment]
Hi, you don't need to preprocess the data. Just download and extract them, and specify the paths in the code.

For example, the extract dataset structure would be like:

```
- ./data
  - GOT-10k
    - train
    - val
    - test
  - LaSOTBenchmark
  - coco
    - train2017
    - val2017
    - annotations
```

**Comment by cifar10** [comment]
Get it ,thank you very much
