### ISSUE TITLE
结果在tracker_benchmark上表现很差

### ISSUE THREAD

**Issue by lishuo-0** [huanglianghua/GlobalTrack#14]
Result of attributes     -- 'GlobalTrack'
        'ALL'   overlap : 10.5%         failures : 10.0
        'BC'    overlap : 10.0%         failures : 10.0
        'DEF'   overlap : 9.9%  failures : 10.0
        'FM'    overlap : 11.2%         failures : 10.0
        'IPR'   overlap : 11.0%         failures : 9.9
        'IV'    overlap : 10.8%         failures : 10.0
        'LR'    overlap : 9.0%  failures : 10.0
        'MB'    overlap : 10.9%         failures : 10.0
        'OCC'   overlap : 9.5%  failures : 10.0
        'OPR'   overlap : 10.2%         failures : 10.0
        'OV'    overlap : 10.9%         failures : 10.0
        'SV'    overlap : 10.8%         failures : 10.0
![8cf167323b9b975113a30fe0c3dc6db](https://user-images.githubusercontent.com/63949701/82780496-f23ccb00-9e89-11ea-934f-647745e405c6.jpg)

**Comment by huanglianghua** [comment]
@lishuo-0 This problem is likely to be caused by format inconsistencies.

The output format of GlobalTrack is [x1, y1, x2, y2]. (upper-left and lower-right coordinates)

The default format of `tracker_benchmark` (from OTB website) is [x1, y1, width, height].

**Comment by lishuo-0** [comment]
在哪里可以该生成的格式呢

**Comment by lishuo-0** [comment]
在哪里可以改生成的格式呢

**Comment by huanglianghua** [comment]
可以在[global_track.py#L76](https://github.com/huanglianghua/GlobalTrack/blob/0c9bd9649ce6006323787e7d6e6a1b88c19eaf80/trackers/global_track.py#L76)加一句：

```Python
results[:, 2:4] = results[:, 2:4] - results[:, 0:2] + 1
```

**Comment by JAYRobotVis** [comment]
The evaluation results of GlobalTrack on DTB70 seem not satisfying.
I've changed the output format before evaluation. Any suggestions for such results?
![image](https://user-images.githubusercontent.com/81427458/112645808-d3301080-8e81-11eb-9f81-befbfac2647a.png)
