### ISSUE TITLE
Hi, would you please release your 'neuron' repo?

### ISSUE THREAD

**Issue by fzh0917** [huanglianghua/GlobalTrack#2]
I saw the library `neuron` in this repo `GlobalTrack`, it seems to an advanced version of the repo `got10k` for visual tracking dataset processing. So, as the title says, do you have a plan to release that repo named 
 as `neuron`? thank you and all of your doing.

**Comment by huanglianghua** [comment]
@fzh0917 Hi, yes, `neuron` is a better replacement and an extension for the got-10k toolkit.

I am still working on this library to make it complete (by, e.g., implementing engines and reproducing popular modules), and will release it when I finished a complete version.

However, you can directly use the current version of `neuron` independently in your works. Just copy the `neuron` folder in your work or run `python setup.py develop` under the `neuron` folder.

**Comment by fzh0917** [comment]
OK, thank you very much.

**Comment by 1071189147** [comment]
> @fzh0917 Hi, yes, `neuron` is a better replacement and an extension for the got-10k toolkit.
> 
> I am still working on this library to make it complete (by, e.g., implementing engines and reproducing popular modules), and will release it when I finished a complete version.
> 
> However, you can directly use the current version of `neuron` independently in your works. Just copy the `neuron` folder in your work or run `python setup.py develop` under the `neuron` folder.



> @fzh0917 Hi, yes, `neuron` is a better replacement and an extension for the got-10k toolkit.
> 
> I am still working on this library to make it complete (by, e.g., implementing engines and reproducing popular modules), and will release it when I finished a complete version.
> 
> However, you can directly use the current version of `neuron` independently in your works. Just copy the `neuron` folder in your work or run `python setup.py develop` under the `neuron` folder.

您好，按照你的方法配置neuron 后，在train_qg_rcnn中 import neuron.ops 仍然是“ No module named 'ops'”,请问这可能是什么原因造成的呢
