### ISSUE TITLE
ImportError: _submodules/mmdetection/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by ntucschen** [huanglianghua/GlobalTrack#3]
hi, 
I got some error: 
`ImportError: _submodules/mmdetection/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration
`
I tried on two computer(1060 and 2080ti), they all got same error.
Can anyone help me?
thanks

你好：
我在1060, 2080ti上 嘗試運作，都獲得同樣的error，能否給予我一點協助，非常感謝

**Comment by ntucschen** [comment]
I solved this error. This error was caused by inconsistent pytorch and cuda version. 
In my case, I use cuda 10.0 ,  so I need to download the corresponding pytorch.

**Comment by 1071189147** [comment]
> 我解决了这个错误。此错误是由pytorch和cuda版本不一致引起的。
> 就我而言，我使用cuda 10.0，所以我需要下载相应的pytorch。

Could you  tell me what's your final version number of Pytorch?
