### ISSUE TITLE
hope you release tracking results on common datasets

### ISSUE THREAD

**Issue by fzh0917** [huanglianghua/GlobalTrack#6]
As the title describes, can you release your tracking results on common datasets? 
Though the paper shows overall results on most long-term datasets, I want to analyze the result on each video of common datasets, especially short-term datasets, such as OTB2015, VOT2018, .etc.
Thank you! 
Best regards!

**Comment by huanglianghua** [comment]
Hi, thank you for the suggestion. We'll consider releasing all available tracking results.

Alternatively, you can also run `tools/test_global_track.py` (change the `evaluators` to different datasets for your need) and run the code to get your results of interest.

**Comment by fzh0917** [comment]
OK. Looking forward to the results, I am manually running it now.
Besides, a small improvement can be done in the `environment.yml` file, the `prefix` parameter value should be dynamic.
