### ISSUE TITLE
OTB-15 demo not performing well and  LaSOTBenchmark not found. 

### ISSUE THREAD

**Issue by ntucschen** [huanglianghua/GlobalTrack#7]
hi,
I have two issues when I run `python test_global_track.py`

1.  the testing data basketball, bird... in OTB-15 not performing well.
I used original set in  test_global_track.py.
`cfg_file = 'configs/qg_rcnn_r50_fpn.py'`
 `ckp_file = 'checkpoints/qg_rcnn_r50_fpn_coco_got10k_lasot.pth'`
The problem of tracking the wrong object is serious (eg., wrong player, wrong bird... ).

2. I got the error OSError: /home/myAccount/data/LaSOTBenchmark/airplane/airplane-1/groundtruth.txt not found

Where to download the LaSOTB benchmark？
or it will download automatically, when I run test_global_track.py.

> Files already downloaded.
> Processing sequence [1/280]: airplane-1...
> Traceback (most recent call last):
>   File "test_global_track.py", line 15, in <module>
>     data.EvaluatorLaSOT(frame_stride=10),
>   File "_submodules/neuron/neuron/data/evaluators/otb_eval.py", line 430, in __init__
>     dataset = datasets.LaSOT(root_dir, subset='test')
>   File "_submodules/neuron/neuron/data/datasets/lasot.py", line 42, in __init__
>     subset=self.subset)
>   File "_submodules/neuron/neuron/data/datasets/dataset.py", line 30, in __init__
>     seq_dict = self._construct_seq_dict(**kwargs)
>   File "_submodules/neuron/neuron/data/datasets/lasot.py", line 69, in _construct_seq_dict
>     anno_files[s], delimiter=',', dtype=np.float32)
>   File "/home/myAccount/miniconda3/envs/globalTrack/lib/python3.7/site-packages/numpy/lib/npyio.py", line 962, in loadtxt
>     fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
>   File "/home/myAccount/miniconda3/envs/globalTrack/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 266, in open
>     return ds.open(path, mode, encoding=encoding, newline=newline)
>   File "/home/myAccount/miniconda3/envs/globalTrack/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 624, in open
>     raise IOError("%s not found." % path)
> OSError: /home/myAccount/data/LaSOTBenchmark/airplane/airplane-1/groundtruth.txt not found.

**Comment by huanglianghua** [comment]
Hi,
1. `GlobalTrack` searches targets globally without relying on temporal information. So it may perform worse when many similar objects appear in a same video.
2. The LaSOTBenchmark can be downloaded from this website: https://cis.temple.edu/lasot/

Alternatively, if you don't want to use LaSOT, just comment `EvaluatorLaSOT` in `tools/test_global_track.py`.
