### ISSUE TITLE
Is there any way to speed up online tracking? 

### ISSUE THREAD

**Issue by klq-Y** [huanglianghua/GlobalTrack#8]
6fps is too slow,and it's runing on a powerful TitanX GPU.

**Comment by huanglianghua** [comment]
There could be several possible ways to speed up GlobalTrack:

1. Using a more efficient backbone by replacing ResNet50 to, e.g., ResNet18/MobileNets/EfficientNets.
2. Reducing the input image size, from (1333, 800) to, e.g., (640, 480).
3. Using a low-precision or quantized model, by converting fp32 weights to fp16 or int8.
4. Combining GlobalTrack with a fast local tracker (e.g., SiamRPN, ATOM). Only run GlobalTrack when local tracker detects a failure.

Hope this helps.

**Comment by klq-Y** [comment]
Thank you very much for your advice.
